
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maeil
    username: "root"
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
