spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:maeil;MODE=MARIADB;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console

itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: fg6a5NWa3mGSAw3hO8m_
    secret: U6Rl5SgtsU

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maeil
    username: "root"
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: fg6a5NWa3mGSAw3hO8m_
    secret: U6Rl5SgtsU
